// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGjJ1IRZ40PBDx8NDV05svxeac9SBBRY',
    appId: '1:1020782246787:web:a63cf6d568a550c09854b6',
    messagingSenderId: '1020782246787',
    projectId: 'shop-2e0ef',
    authDomain: 'shop-2e0ef.firebaseapp.com',
    storageBucket: 'shop-2e0ef.appspot.com',
    measurementId: 'G-BZHBT0MYM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wmbuaxa04dlCwxRrX92U2Zf2nLAtGbc',
    appId: '1:1020782246787:android:b5956e715260cd269854b6',
    messagingSenderId: '1020782246787',
    projectId: 'shop-2e0ef',
    storageBucket: 'shop-2e0ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-Gj5cuoZBPxWLx1JxkseKswjenpJN2c',
    appId: '1:1020782246787:ios:3a5b4bca59f6f0ce9854b6',
    messagingSenderId: '1020782246787',
    projectId: 'shop-2e0ef',
    storageBucket: 'shop-2e0ef.appspot.com',
    iosBundleId: 'com.example.asrooshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-Gj5cuoZBPxWLx1JxkseKswjenpJN2c',
    appId: '1:1020782246787:ios:45216711c60a85319854b6',
    messagingSenderId: '1020782246787',
    projectId: 'shop-2e0ef',
    storageBucket: 'shop-2e0ef.appspot.com',
    iosBundleId: 'com.example.asrooshop.RunnerTests',
  );
}
